/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface ContactInquiry {
    id: InquiryId;
    name: string;
    createdAt: Time;
    email?: string;
    message: string;
    phone: string;
}
export type Time = bigint;
export type GalleryId = number;
export interface User {
    id: UserId;
    principal: Principal;
    name: string;
    createdAt: Time;
    role: Role;
    phone: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Crop {
    id: CropId;
    status: CropStatus;
    createdAt: Time;
    farmerPrincipal: Principal;
    description: string;
    imageUrl: ExternalBlob;
    quantity: bigint;
    cropName: string;
    price: bigint;
    farmerPhone: string;
    farmerName: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Order {
    id: OrderId;
    status: OrderStatus;
    createdAt: Time;
    buyerPhone: string;
    cropId: CropId;
    message: string;
    buyerPrincipal: Principal;
    buyerName: string;
}
export type UserId = number;
export type InquiryId = number;
export type CropId = number;
export interface CropInput {
    description: string;
    quantity: bigint;
    cropName: string;
    image: ExternalBlob;
    price: bigint;
    farmerPhone: string;
    farmerName: string;
}
export interface Notice {
    id: NoticeId;
    title: string;
    postedBy: string;
    content: string;
    createdAt: Time;
}
export interface GalleryItem {
    id: GalleryId;
    createdAt: Time;
    imageUrl: string;
    caption: string;
}
export type NoticeId = number;
export type OrderId = number;
export interface UserProfile {
    name: string;
    createdAt: Time;
    role: Role;
    phone: string;
}
export enum CropStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum OrderStatus {
    pending = "pending",
    rejected = "rejected",
    accepted = "accepted"
}
export enum Role {
    admin = "admin",
    buyer = "buyer",
    farmer = "farmer"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    /**
     * / Add a new crop listing (authenticated users only; status starts as pending).
     */
    addCrop(crop: CropInput): Promise<CropId>;
    /**
     * / Add a gallery item (admin only).
     */
    addGalleryItem(imageUrl: string, caption: string): Promise<GalleryId>;
    /**
     * / Add a notice (admin only).
     */
    addNotice(title: string, content: string, postedBy: string): Promise<NoticeId>;
    /**
     * / Approve a crop listing (admin only).
     */
    approveCrop(cropId: CropId): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Delete a crop listing. Only the owning farmer or an admin may delete it.
     */
    deleteCrop(cropId: CropId): Promise<void>;
    /**
     * / Delete a gallery item (admin only).
     */
    deleteGalleryItem(galleryId: GalleryId): Promise<void>;
    /**
     * / Delete a notice (admin only).
     */
    deleteNotice(noticeId: NoticeId): Promise<void>;
    /**
     * / Edit an existing crop listing. Only the farmer who owns it may edit it.
     */
    editCrop(cropId: CropId, crop: CropInput): Promise<void>;
    /**
     * / Return all approved crop listings (public, no auth required).
     */
    getAllApprovedCrops(): Promise<Array<Crop>>;
    /**
     * / Return all contact inquiries (admin only).
     */
    getAllContactInquiries(): Promise<Array<ContactInquiry>>;
    /**
     * / Return all crops regardless of status (admin only).
     */
    getAllCrops(): Promise<Array<Crop>>;
    /**
     * / Return all gallery items (public, no auth required).
     */
    getAllGalleryItems(): Promise<Array<GalleryItem>>;
    /**
     * / Return all notices in reverse chronological order (public, no auth required).
     */
    getAllNotices(): Promise<Array<Notice>>;
    /**
     * / Return all orders (admin only).
     */
    getAllOrders(): Promise<Array<Order>>;
    /**
     * / Return all registered users (admin only).
     */
    getAllUsers(): Promise<Array<User>>;
    /**
     * / Return the profile of the calling authenticated user.
     */
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Return a single crop by ID. Pending/rejected crops are only visible to
     * / the owning farmer or an admin.
     */
    getCropById(cropId: CropId): Promise<Crop | null>;
    /**
     * / Return all crops belonging to the calling farmer.
     */
    getMyCrops(): Promise<Array<Crop>>;
    /**
     * / Return all orders placed by the calling buyer.
     */
    getMyOrders(): Promise<Array<Order>>;
    /**
     * / Return all orders for crops owned by the calling farmer.
     */
    getOrdersForMycrops(): Promise<Array<Order>>;
    /**
     * / Return all pending crops (admin only).
     */
    getPendingCrops(): Promise<Array<Crop>>;
    /**
     * / Fetch another user's profile. Callers may only view their own profile
     * / unless they are an admin.
     */
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / Place an order request for an approved crop (authenticated users only).
     */
    placeOrder(cropId: CropId, buyerName: string, buyerPhone: string, message: string): Promise<OrderId>;
    /**
     * / Register (or update) the calling user's full record.
     */
    registerUser(name: string, phone: string, role: Role): Promise<number>;
    /**
     * / Reject a crop listing (admin only).
     */
    rejectCrop(cropId: CropId): Promise<void>;
    /**
     * / Persist (create or update) the profile of the calling authenticated user.
     */
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    /**
     * / Submit a contact inquiry. Open to everyone including guests — no auth
     * / check required so that anonymous visitors can also reach out.
     */
    submitContactInquiry(name: string, phone: string, email: string | null, message: string): Promise<InquiryId>;
    /**
     * / Update the status of an order. Only the farmer who owns the crop or an
     * / admin may accept/reject an order.
     */
    updateOrderStatus(orderId: OrderId, status: OrderStatus): Promise<void>;
}
import type { ContactInquiry as _ContactInquiry, Crop as _Crop, CropId as _CropId, CropInput as _CropInput, CropStatus as _CropStatus, ExternalBlob as _ExternalBlob, InquiryId as _InquiryId, Order as _Order, OrderId as _OrderId, OrderStatus as _OrderStatus, Role as _Role, Time as _Time, User as _User, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCrop(arg0: CropInput): Promise<CropId> {
        if (this.processError) {
            try {
                const result = await this.actor.addCrop(await to_candid_CropInput_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCrop(await to_candid_CropInput_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addGalleryItem(arg0: string, arg1: string): Promise<GalleryId> {
        if (this.processError) {
            try {
                const result = await this.actor.addGalleryItem(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGalleryItem(arg0, arg1);
            return result;
        }
    }
    async addNotice(arg0: string, arg1: string, arg2: string): Promise<NoticeId> {
        if (this.processError) {
            try {
                const result = await this.actor.addNotice(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNotice(arg0, arg1, arg2);
            return result;
        }
    }
    async approveCrop(arg0: CropId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveCrop(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveCrop(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteCrop(arg0: CropId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCrop(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCrop(arg0);
            return result;
        }
    }
    async deleteGalleryItem(arg0: GalleryId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGalleryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGalleryItem(arg0);
            return result;
        }
    }
    async deleteNotice(arg0: NoticeId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNotice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNotice(arg0);
            return result;
        }
    }
    async editCrop(arg0: CropId, arg1: CropInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editCrop(arg0, await to_candid_CropInput_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editCrop(arg0, await to_candid_CropInput_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllApprovedCrops(): Promise<Array<Crop>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllApprovedCrops();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllApprovedCrops();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllContactInquiries(): Promise<Array<ContactInquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContactInquiries();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContactInquiries();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCrops(): Promise<Array<Crop>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCrops();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCrops();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllGalleryItems(): Promise<Array<GalleryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGalleryItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGalleryItems();
            return result;
        }
    }
    async getAllNotices(): Promise<Array<Notice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNotices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNotices();
            return result;
        }
    }
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCropById(arg0: CropId): Promise<Crop | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCropById(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCropById(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyCrops(): Promise<Array<Crop>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCrops();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCrops();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOrders();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOrders();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrdersForMycrops(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersForMycrops();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersForMycrops();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingCrops(): Promise<Array<Crop>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingCrops();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingCrops();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async placeOrder(arg0: CropId, arg1: string, arg2: string, arg3: string): Promise<OrderId> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: Role): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, to_candid_Role_n39(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, to_candid_Role_n39(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async rejectCrop(arg0: CropId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectCrop(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectCrop(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n41(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n41(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitContactInquiry(arg0: string, arg1: string, arg2: string | null, arg3: string): Promise<InquiryId> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactInquiry(arg0, arg1, to_candid_opt_n43(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactInquiry(arg0, arg1, to_candid_opt_n43(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async updateOrderStatus(arg0: OrderId, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n44(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n44(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ContactInquiry_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContactInquiry): ContactInquiry {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_CropStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CropStatus): CropStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
async function from_candid_Crop_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Crop): Promise<Crop> {
    return await from_candid_record_n15(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_OrderStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_User_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n34(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Crop]): Promise<Crop | null> {
    return value.length === 0 ? null : await from_candid_Crop_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CropId;
    status: _CropStatus;
    createdAt: _Time;
    farmerPrincipal: Principal;
    description: string;
    imageUrl: _ExternalBlob;
    quantity: bigint;
    cropName: string;
    price: bigint;
    farmerPhone: string;
    farmerName: string;
}): Promise<{
    id: CropId;
    status: CropStatus;
    createdAt: Time;
    farmerPrincipal: Principal;
    description: string;
    imageUrl: ExternalBlob;
    quantity: bigint;
    cropName: string;
    price: bigint;
    farmerPhone: string;
    farmerName: string;
}> {
    return {
        id: value.id,
        status: from_candid_CropStatus_n16(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        farmerPrincipal: value.farmerPrincipal,
        description: value.description,
        imageUrl: await from_candid_ExternalBlob_n18(_uploadFile, _downloadFile, value.imageUrl),
        quantity: value.quantity,
        cropName: value.cropName,
        price: value.price,
        farmerPhone: value.farmerPhone,
        farmerName: value.farmerName
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _InquiryId;
    name: string;
    createdAt: _Time;
    email: [] | [string];
    message: string;
    phone: string;
}): {
    id: InquiryId;
    name: string;
    createdAt: Time;
    email?: string;
    message: string;
    phone: string;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        email: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.email)),
        message: value.message,
        phone: value.phone
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    status: _OrderStatus;
    createdAt: _Time;
    buyerPhone: string;
    cropId: _CropId;
    message: string;
    buyerPrincipal: Principal;
    buyerName: string;
}): {
    id: OrderId;
    status: OrderStatus;
    createdAt: Time;
    buyerPhone: string;
    cropId: CropId;
    message: string;
    buyerPrincipal: Principal;
    buyerName: string;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n26(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        buyerPhone: value.buyerPhone,
        cropId: value.cropId,
        message: value.message,
        buyerPrincipal: value.buyerPrincipal,
        buyerName: value.buyerName
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    principal: Principal;
    name: string;
    createdAt: _Time;
    role: _Role;
    phone: string;
}): {
    id: UserId;
    principal: Principal;
    name: string;
    createdAt: Time;
    role: Role;
    phone: string;
} {
    return {
        id: value.id,
        principal: value.principal,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_Role_n31(_uploadFile, _downloadFile, value.role),
        phone: value.phone
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    createdAt: _Time;
    role: _Role;
    phone: string;
}): {
    name: string;
    createdAt: Time;
    role: Role;
    phone: string;
} {
    return {
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_Role_n31(_uploadFile, _downloadFile, value.role),
        phone: value.phone
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): CropStatus {
    return "pending" in value ? CropStatus.pending : "approved" in value ? CropStatus.approved : "rejected" in value ? CropStatus.rejected : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    rejected: null;
} | {
    accepted: null;
}): OrderStatus {
    return "pending" in value ? OrderStatus.pending : "rejected" in value ? OrderStatus.rejected : "accepted" in value ? OrderStatus.accepted : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    buyer: null;
} | {
    farmer: null;
}): Role {
    return "admin" in value ? Role.admin : "buyer" in value ? Role.buyer : "farmer" in value ? Role.farmer : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Crop>): Promise<Array<Crop>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Crop_n14(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContactInquiry>): Array<ContactInquiry> {
    return value.map((x)=>from_candid_ContactInquiry_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n29(_uploadFile, _downloadFile, x));
}
async function to_candid_CropInput_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CropInput): Promise<_CropInput> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_OrderStatus_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n42(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    createdAt: Time;
    role: Role;
    phone: string;
}): {
    name: string;
    createdAt: _Time;
    role: _Role;
    phone: string;
} {
    return {
        name: value.name,
        createdAt: value.createdAt,
        role: to_candid_Role_n39(_uploadFile, _downloadFile, value.role),
        phone: value.phone
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    description: string;
    quantity: bigint;
    cropName: string;
    image: ExternalBlob;
    price: bigint;
    farmerPhone: string;
    farmerName: string;
}): Promise<{
    description: string;
    quantity: bigint;
    cropName: string;
    image: _ExternalBlob;
    price: bigint;
    farmerPhone: string;
    farmerName: string;
}> {
    return {
        description: value.description,
        quantity: value.quantity,
        cropName: value.cropName,
        image: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.image),
        price: value.price,
        farmerPhone: value.farmerPhone,
        farmerName: value.farmerName
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    admin: null;
} | {
    buyer: null;
} | {
    farmer: null;
} {
    return value == Role.admin ? {
        admin: null
    } : value == Role.buyer ? {
        buyer: null
    } : value == Role.farmer ? {
        farmer: null
    } : value;
}
function to_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    pending: null;
} | {
    rejected: null;
} | {
    accepted: null;
} {
    return value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.rejected ? {
        rejected: null
    } : value == OrderStatus.accepted ? {
        accepted: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
