/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CropInput = IDL.Record({
  'description' : IDL.Text,
  'quantity' : IDL.Nat,
  'cropName' : IDL.Text,
  'image' : ExternalBlob,
  'price' : IDL.Nat,
  'farmerPhone' : IDL.Text,
  'farmerName' : IDL.Text,
});
export const CropId = IDL.Nat32;
export const GalleryId = IDL.Nat32;
export const NoticeId = IDL.Nat32;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CropStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Time = IDL.Int;
export const Crop = IDL.Record({
  'id' : CropId,
  'status' : CropStatus,
  'createdAt' : Time,
  'farmerPrincipal' : IDL.Principal,
  'description' : IDL.Text,
  'imageUrl' : ExternalBlob,
  'quantity' : IDL.Nat,
  'cropName' : IDL.Text,
  'price' : IDL.Nat,
  'farmerPhone' : IDL.Text,
  'farmerName' : IDL.Text,
});
export const InquiryId = IDL.Nat32;
export const ContactInquiry = IDL.Record({
  'id' : InquiryId,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const GalleryItem = IDL.Record({
  'id' : GalleryId,
  'createdAt' : Time,
  'imageUrl' : IDL.Text,
  'caption' : IDL.Text,
});
export const Notice = IDL.Record({
  'id' : NoticeId,
  'title' : IDL.Text,
  'postedBy' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Time,
});
export const OrderId = IDL.Nat32;
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'createdAt' : Time,
  'buyerPhone' : IDL.Text,
  'cropId' : CropId,
  'message' : IDL.Text,
  'buyerPrincipal' : IDL.Principal,
  'buyerName' : IDL.Text,
});
export const UserId = IDL.Nat32;
export const Role = IDL.Variant({
  'admin' : IDL.Null,
  'buyer' : IDL.Null,
  'farmer' : IDL.Null,
});
export const User = IDL.Record({
  'id' : UserId,
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'role' : Role,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Time,
  'role' : Role,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCrop' : IDL.Func([CropInput], [CropId], []),
  'addGalleryItem' : IDL.Func([IDL.Text, IDL.Text], [GalleryId], []),
  'addNotice' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [NoticeId], []),
  'approveCrop' : IDL.Func([CropId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCrop' : IDL.Func([CropId], [], []),
  'deleteGalleryItem' : IDL.Func([GalleryId], [], []),
  'deleteNotice' : IDL.Func([NoticeId], [], []),
  'editCrop' : IDL.Func([CropId, CropInput], [], []),
  'getAllApprovedCrops' : IDL.Func([], [IDL.Vec(Crop)], ['query']),
  'getAllContactInquiries' : IDL.Func([], [IDL.Vec(ContactInquiry)], ['query']),
  'getAllCrops' : IDL.Func([], [IDL.Vec(Crop)], ['query']),
  'getAllGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getAllNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCropById' : IDL.Func([CropId], [IDL.Opt(Crop)], ['query']),
  'getMyCrops' : IDL.Func([], [IDL.Vec(Crop)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrdersForMycrops' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getPendingCrops' : IDL.Func([], [IDL.Vec(Crop)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func(
      [CropId, IDL.Text, IDL.Text, IDL.Text],
      [OrderId],
      [],
    ),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text, Role], [IDL.Nat32], []),
  'rejectCrop' : IDL.Func([CropId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
      [InquiryId],
      [],
    ),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CropInput = IDL.Record({
    'description' : IDL.Text,
    'quantity' : IDL.Nat,
    'cropName' : IDL.Text,
    'image' : ExternalBlob,
    'price' : IDL.Nat,
    'farmerPhone' : IDL.Text,
    'farmerName' : IDL.Text,
  });
  const CropId = IDL.Nat32;
  const GalleryId = IDL.Nat32;
  const NoticeId = IDL.Nat32;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CropStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Time = IDL.Int;
  const Crop = IDL.Record({
    'id' : CropId,
    'status' : CropStatus,
    'createdAt' : Time,
    'farmerPrincipal' : IDL.Principal,
    'description' : IDL.Text,
    'imageUrl' : ExternalBlob,
    'quantity' : IDL.Nat,
    'cropName' : IDL.Text,
    'price' : IDL.Nat,
    'farmerPhone' : IDL.Text,
    'farmerName' : IDL.Text,
  });
  const InquiryId = IDL.Nat32;
  const ContactInquiry = IDL.Record({
    'id' : InquiryId,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const GalleryItem = IDL.Record({
    'id' : GalleryId,
    'createdAt' : Time,
    'imageUrl' : IDL.Text,
    'caption' : IDL.Text,
  });
  const Notice = IDL.Record({
    'id' : NoticeId,
    'title' : IDL.Text,
    'postedBy' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Time,
  });
  const OrderId = IDL.Nat32;
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'createdAt' : Time,
    'buyerPhone' : IDL.Text,
    'cropId' : CropId,
    'message' : IDL.Text,
    'buyerPrincipal' : IDL.Principal,
    'buyerName' : IDL.Text,
  });
  const UserId = IDL.Nat32;
  const Role = IDL.Variant({
    'admin' : IDL.Null,
    'buyer' : IDL.Null,
    'farmer' : IDL.Null,
  });
  const User = IDL.Record({
    'id' : UserId,
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'role' : Role,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : Time,
    'role' : Role,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCrop' : IDL.Func([CropInput], [CropId], []),
    'addGalleryItem' : IDL.Func([IDL.Text, IDL.Text], [GalleryId], []),
    'addNotice' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [NoticeId], []),
    'approveCrop' : IDL.Func([CropId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCrop' : IDL.Func([CropId], [], []),
    'deleteGalleryItem' : IDL.Func([GalleryId], [], []),
    'deleteNotice' : IDL.Func([NoticeId], [], []),
    'editCrop' : IDL.Func([CropId, CropInput], [], []),
    'getAllApprovedCrops' : IDL.Func([], [IDL.Vec(Crop)], ['query']),
    'getAllContactInquiries' : IDL.Func(
        [],
        [IDL.Vec(ContactInquiry)],
        ['query'],
      ),
    'getAllCrops' : IDL.Func([], [IDL.Vec(Crop)], ['query']),
    'getAllGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getAllNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCropById' : IDL.Func([CropId], [IDL.Opt(Crop)], ['query']),
    'getMyCrops' : IDL.Func([], [IDL.Vec(Crop)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrdersForMycrops' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getPendingCrops' : IDL.Func([], [IDL.Vec(Crop)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func(
        [CropId, IDL.Text, IDL.Text, IDL.Text],
        [OrderId],
        [],
      ),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text, Role], [IDL.Nat32], []),
    'rejectCrop' : IDL.Func([CropId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
        [InquiryId],
        [],
      ),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };