/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactInquiry {
  'id' : InquiryId,
  'name' : string,
  'createdAt' : Time,
  'email' : [] | [string],
  'message' : string,
  'phone' : string,
}
export interface Crop {
  'id' : CropId,
  'status' : CropStatus,
  'createdAt' : Time,
  'farmerPrincipal' : Principal,
  'description' : string,
  'imageUrl' : ExternalBlob,
  'quantity' : bigint,
  'cropName' : string,
  'price' : bigint,
  'farmerPhone' : string,
  'farmerName' : string,
}
export type CropId = number;
export interface CropInput {
  'description' : string,
  'quantity' : bigint,
  'cropName' : string,
  'image' : ExternalBlob,
  'price' : bigint,
  'farmerPhone' : string,
  'farmerName' : string,
}
export type CropStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type ExternalBlob = Uint8Array;
export type GalleryId = number;
export interface GalleryItem {
  'id' : GalleryId,
  'createdAt' : Time,
  'imageUrl' : string,
  'caption' : string,
}
export type InquiryId = number;
export interface Notice {
  'id' : NoticeId,
  'title' : string,
  'postedBy' : string,
  'content' : string,
  'createdAt' : Time,
}
export type NoticeId = number;
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'createdAt' : Time,
  'buyerPhone' : string,
  'cropId' : CropId,
  'message' : string,
  'buyerPrincipal' : Principal,
  'buyerName' : string,
}
export type OrderId = number;
export type OrderStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export type Role = { 'admin' : null } |
  { 'buyer' : null } |
  { 'farmer' : null };
export type Time = bigint;
export interface User {
  'id' : UserId,
  'principal' : Principal,
  'name' : string,
  'createdAt' : Time,
  'role' : Role,
  'phone' : string,
}
export type UserId = number;
export interface UserProfile {
  'name' : string,
  'createdAt' : Time,
  'role' : Role,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Add a new crop listing (authenticated users only; status starts as pending).
   */
  'addCrop' : ActorMethod<[CropInput], CropId>,
  /**
   * / Add a gallery item (admin only).
   */
  'addGalleryItem' : ActorMethod<[string, string], GalleryId>,
  /**
   * / Add a notice (admin only).
   */
  'addNotice' : ActorMethod<[string, string, string], NoticeId>,
  /**
   * / Approve a crop listing (admin only).
   */
  'approveCrop' : ActorMethod<[CropId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Delete a crop listing. Only the owning farmer or an admin may delete it.
   */
  'deleteCrop' : ActorMethod<[CropId], undefined>,
  /**
   * / Delete a gallery item (admin only).
   */
  'deleteGalleryItem' : ActorMethod<[GalleryId], undefined>,
  /**
   * / Delete a notice (admin only).
   */
  'deleteNotice' : ActorMethod<[NoticeId], undefined>,
  /**
   * / Edit an existing crop listing. Only the farmer who owns it may edit it.
   */
  'editCrop' : ActorMethod<[CropId, CropInput], undefined>,
  /**
   * / Return all approved crop listings (public, no auth required).
   */
  'getAllApprovedCrops' : ActorMethod<[], Array<Crop>>,
  /**
   * / Return all contact inquiries (admin only).
   */
  'getAllContactInquiries' : ActorMethod<[], Array<ContactInquiry>>,
  /**
   * / Return all crops regardless of status (admin only).
   */
  'getAllCrops' : ActorMethod<[], Array<Crop>>,
  /**
   * / Return all gallery items (public, no auth required).
   */
  'getAllGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  /**
   * / Return all notices in reverse chronological order (public, no auth required).
   */
  'getAllNotices' : ActorMethod<[], Array<Notice>>,
  /**
   * / Return all orders (admin only).
   */
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  /**
   * / Return all registered users (admin only).
   */
  'getAllUsers' : ActorMethod<[], Array<User>>,
  /**
   * / Return the profile of the calling authenticated user.
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Return a single crop by ID. Pending/rejected crops are only visible to
   * / the owning farmer or an admin.
   */
  'getCropById' : ActorMethod<[CropId], [] | [Crop]>,
  /**
   * / Return all crops belonging to the calling farmer.
   */
  'getMyCrops' : ActorMethod<[], Array<Crop>>,
  /**
   * / Return all orders placed by the calling buyer.
   */
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  /**
   * / Return all orders for crops owned by the calling farmer.
   */
  'getOrdersForMycrops' : ActorMethod<[], Array<Order>>,
  /**
   * / Return all pending crops (admin only).
   */
  'getPendingCrops' : ActorMethod<[], Array<Crop>>,
  /**
   * / Fetch another user's profile. Callers may only view their own profile
   * / unless they are an admin.
   */
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Place an order request for an approved crop (authenticated users only).
   */
  'placeOrder' : ActorMethod<[CropId, string, string, string], OrderId>,
  /**
   * / Register (or update) the calling user's full record.
   */
  'registerUser' : ActorMethod<[string, string, Role], number>,
  /**
   * / Reject a crop listing (admin only).
   */
  'rejectCrop' : ActorMethod<[CropId], undefined>,
  /**
   * / Persist (create or update) the profile of the calling authenticated user.
   */
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Submit a contact inquiry. Open to everyone including guests — no auth
   * / check required so that anonymous visitors can also reach out.
   */
  'submitContactInquiry' : ActorMethod<
    [string, string, [] | [string], string],
    InquiryId
  >,
  /**
   * / Update the status of an order. Only the farmer who owns the crop or an
   * / admin may accept/reject an order.
   */
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];